import { NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase/admin';
import { generateCouponCode, randomDiscountPercentage, endOfDayIST } from '@/lib/daily-coupon';

const MAX_ATTEMPTS = 5;

// Triggered by Vercel Cron (see vercel.json) on Mon/Wed/Fri mornings. Creates one coupon with a
// random 5-12% discount, valid until midnight IST the same day, for the admin to post on social
// media that day (posting itself stays manual — no code change removes that step).
export async function GET(request) {
  const authHeader = request.headers.get('authorization') || '';
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const discountPercentage = randomDiscountPercentage();
  const couponsRef = adminDb().collection('coupons');

  let code = null;
  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    const candidate = generateCouponCode(discountPercentage);
    const existing = await couponsRef.where('code', '==', candidate).limit(1).get();
    if (existing.empty) {
      code = candidate;
      break;
    }
  }

  if (!code) {
    return NextResponse.json({ error: 'Could not generate a unique coupon code' }, { status: 500 });
  }

  const expiryDate = endOfDayIST();
  await couponsRef.add({
    code,
    discountPercentage,
    expiryDate,
    createdAt: new Date(),
    autoGenerated: true,
  });

  return NextResponse.json({ code, discountPercentage, expiryDate });
}
